### ISSUE TITLE
Confusion with `CancelledJobRetentionPeriod` and `DiscardedJobRetentionPeriod`

### ISSUE THREAD

**Issue by BolajiOlajide** [riverqueue/river#118]
Thank you so much for river. I'm loving it so far.

While integrating this into one of my projects, I was confused by two options in `river.Config` arg passed into `river.NewClient`.

![CleanShot 2023-12-17 at 14 30 13@2x](https://github.com/riverqueue/river/assets/25608335/1e10ee17-5b0c-4ed7-91dc-24a30139de4e)

From the documentation, [DiscardedJobRetentionPeriod](https://sourcegraph.com/github.com/riverqueue/river@1693561488124093b3b30bcd940fc2b61a43709c/-/blob/client.go?L77) and [CancelledJobRetentionPeriod](https://sourcegraph.com/github.com/riverqueue/river@1693561488124093b3b30bcd940fc2b61a43709c/-/blob/client.go?L65) seem to be doing the same thing, can the team provide clarity on this.

**Comment by bgentry** [comment]
Oops, looks like a documentation error as we pushed for launch 😬 I’ll fix that today.

In short there are 3 different retention periods for jobs in different states: https://riverqueue.com/docs/maintenance-services

Each is customizable. This allows you to have longer or longer retention times as desired for i.e. discarded jobs which failed repeatedly until they hit their max number of attempts, or shorter times for jobs which completed successfully.

**Comment by BolajiOlajide** [comment]
Hey @bgentry 

This is unrelated to this issue - Is there a roadmap one can have a look at to see how they can contribute to this project?
I'd love to contribute to `river` as I currently also make use of it in one of my side projects.

**Comment by bgentry** [comment]
@BolajiOlajide at the moment we don’t have an established roadmap other than what’s being voted on in the discussions section. We do have lots of ideas and a handful of things in progress though. Would love to hear more about what you’re looking for & what would make your life easier!
