### ISSUE TITLE
Client's `Schema` config does nothing

### ISSUE THREAD

**Issue by brandur** [riverqueue/river#15]
Unless I'm mistaken, the `Schema` option that can be sent to a client doesn't do anything.

I think all we need to do is to make sure to run `SET SCHEMA 'xxx'` on every new connection?

Also, even if this feature did work, the migration tool doesn't currently support an alternate schema, so that needs to be corrected too.

cc @bgentry

**Comment by bgentry** [comment]
Ah, yeah we never got around to implementing this. We can either nuke the setting for now, or try to make the required fixes to make it work. I expect it will come up as a requested setting.

Even without explicit support for this, the user could already be setting a `search_path` in the [`pgx.ConnConfig` `RuntimeParams`](https://pkg.go.dev/github.com/jackc/pgx#ConnConfig) and any conns we check out will already be configured to use the specified schema. So I'm not actually clear whether we _need_ a setting for this even if we support it.

**Comment by brandur** [comment]
Actually, good point on using pgx to configure it — I kinda like that, although we'd definitely need a section in the docs explaining how to do it because it wouldn't be obvious.

The CLI migrator would probably still need to support a `--schema` option, but the eventual more flexible `rivermigrate` package that takes a pgx connection could use the pgx technique.

**Comment by bgentry** [comment]
@brandur you can actually set `search_path` as part of the connection URL if desired: https://github.com/jackc/pgx/issues/1013#issuecomment-846431794

So maybe the CLI already works with it too?

**Comment by brandur** [comment]
Oh awesome! Another thing we'll have to document because it's pretty non-obvious, but yes, that should solve our problems for now.
