### ISSUE TITLE
API naming inconsistency

### ISSUE THREAD

**Issue by bgentry** [riverqueue/river#150]
I realized while writing up the changelog entry for https://github.com/riverqueue/river/pull/117 that I had named that API `JobList()`, while I named the API from #141 `Cancel()` with no `Job` prefix. We have other job-related query APIs to add like `Get`, `RetryImmediately`, etc. These should probably all either _have_ a prefix or _not_ have one, but without inconsistency.

Thoughts @brandur? Should be an easy fix as we are still prerelease on the new API.

**Comment by brandur** [comment]
@bgentry Yeah +1 – aside from the consistency, IMO having a shared prefix also makes things easier to find with tab complete. As you might expect, I'd vote for the `Job*` prefix being added to everything. Basic actions like `List` or `Get` especially just seem way too generic to me without being attached to a noun.
