### ISSUE TITLE
Unique periodic jobs

### ISSUE THREAD

**Issue by atoi** [riverqueue/river#161]
The documentation states it is possible to combine unique and periodic jobs:

> Fortunately, many of these concerns can be addressed by combining periodic jobs with [unique jobs](https://riverqueue.com/docs/unique-jobs) and the RunOnStart option. For example, a job which is configured to be unique at the hourly level will only enqueue once in that hour no matter how many times it's attempted.

Unfortunately I was not able to make it work. After some source code studying I found out that periodic jobs are inserted using `JobInsertMany`. That explains why uniqueness does not take effect, as the docs say:

> ...which is why job uniqueness is not supported on [batch insertion](https://riverqueue.com/docs/batch-job-insertion).

Is it something that needs to be fixed, or am I just missing something?

**Comment by bgentry** [comment]
Hi @atoi, thank you for reporting! Let me confirm with @brandur but this seems like a bug. The periodic job functionality should probably be inserting jobs one-at-a-time for exactly this reason.

**Comment by brandur** [comment]
Discussed with Blake. I'll take the fix on this one.

**Comment by brandur** [comment]
[Fixed in 0.0.17](https://github.com/riverqueue/river/blob/master/CHANGELOG.md#0017---2024-01-22).
