### ISSUE TITLE
Enqueue problem (PostgreSQL 22P02)

### ISSUE THREAD

**Issue by lexor** [riverqueue/river#171]
Have been playing around with River and I get an error when adding a job to the queue. I define 3 string arg as job args. 

The error I received is as follows: `error getting unique job: ERROR: invalid input syntax for type json (SQLSTATE 22P02)`

```go
type ExampleJobArgs struct {
	Email  string `json:"email"`
	UserID string `json:"user_id"`
}

func (ExampleJobArgs) Kind() string {
	return "activation_email"
}

func (ExampleJobArgs) InsertOpts() river.InsertOpts {
	return river.InsertOpts{
		UniqueOpts: river.UniqueOpts{
			ByArgs:   true,
			ByPeriod: 4 * time.Hour,
		},
	}
}

// ...

```

```go
type api struct { queue *river.Client[pgx.Tx] }

queue, err := river.NewClient(riverpgxv5.New(postgres), &river.Config{})
if err != nil {
	panic(err)
}

// ...

func (a *api) enqueueHandler(w http.ResponseWriter, r *http.Request) {
	ctx, cancel := context.WithCancel(r.Context())
	defer cancel()

	if _, err = a.queue.Insert(ctx, worker.ExampleJobArgs{
		Email:    "foo@bar.tld",
		UserID:  "1",
	}, nil); err != nil {
		// ...
	}

	// ...
}
```

My periodic jobs works correctly, but I only get this error when enqueueing from API.

**Comment by brandur** [comment]
Odd, so the unique query isn't do anything too exotic. Basically just encoding JSON. Here it is:

``` go
			if params.UniqueByArgs {
				advisoryLockHash.Write([]byte("&args="))
				advisoryLockHash.Write(params.EncodedArgs)

				getParams.Args = params.EncodedArgs
				getParams.ByArgs = true
			}
```

Do you want to try doing a `json.Marshal` on your input `ActivationEmailArgs`, print in, and see if anything in there looks odd?

If not, maybe try removing each of the fields one at a time, and see if any one of them seems to be the offender? (It's probably `email`? But just a guess.)

**Comment by lexor** [comment]
@brandur I tried already removed all args but facing same error.

```
_, err := a.queue.Insert(ctx, worker.ExampleJobArgs{}, nil)

...

type ExampleJobArgs struct {}

func (ExampleJobArgs) Kind() string {
	return "example"
}

func (ExampleJobArgs) InsertOpts() river.InsertOpts {
	return river.InsertOpts{
		UniqueOpts: river.UniqueOpts{
			ByArgs:   true,
			ByPeriod: 4 * time.Hour,
		},
	}
}

type ExampleJobWorker struct {
	river.WorkerDefaults[ExampleJobArgs]
}

func (w *ExampleJobWorker) Work(
	ctx context.Context,
	job *river.Job[ExampleJobArgs],
) error {
	return nil
}
```

**Comment by bgentry** [comment]
Are you running this locally? I’m wondering if the Postgres server logs might reveal something about the value that’s causing the issue.

**Comment by lexor** [comment]
@bgentry Yes, running on docker.

```sql
// river.InsertOpts{UniqueOpts: river.UniqueOpts{ByArgs: true, ByPeriod: 4 * time.Hour}}
2024-01-22 14:13:31.536 UTC [8745] ERROR:  invalid input syntax for type json at character 296
2024-01-22 14:13:31.536 UTC [8745] DETAIL:  Token "\" is invalid.
2024-01-22 14:13:31.536 UTC [8745] CONTEXT:  JSON data, line 1: \...
2024-01-22 14:13:31.536 UTC [8745] STATEMENT:  -- name: JobGetByKindAndUniqueProperties :one
	SELECT id, args, attempt, attempted_at, attempted_by, created_at, errors, finalized_at, kind, max_attempts, metadata, priority, queue, state, scheduled_at, tags
	FROM river_job
	WHERE kind = 'activation_email'
	  AND CASE WHEN 't'::boolean THEN args = '\x7b7d' ELSE true END
	  AND CASE WHEN 't'::boolean THEN tstzrange('2024-01-22 12:00:00Z'::timestamptz, '2024-01-22 16:00:00Z'::timestamptz, '[)') @> created_at ELSE true END
	  AND CASE WHEN 'f'::boolean THEN queue = '' ELSE true END
	  AND CASE WHEN 't'::boolean THEN state::text = any('{available,completed,running,retryable,scheduled}'::text[]) ELSE true END

// river.InsertOpts{}
2024-01-22 14:14:25.253 UTC [8782] ERROR:  invalid input syntax for type json at character 225
2024-01-22 14:14:25.253 UTC [8782] DETAIL:  Token "\" is invalid.
2024-01-22 14:14:25.253 UTC [8782] CONTEXT:  JSON data, line 1: \...
2024-01-22 14:14:25.253 UTC [8782] STATEMENT:  -- name: JobInsert :one
	INSERT INTO river_job(
	  args,
	  attempt,
	  attempted_at,
	  created_at,
	  errors,
	  finalized_at,
	  kind,
	  max_attempts,
	  metadata,
	  priority,
	  queue,
	  scheduled_at,
	  state,
	  tags
	) VALUES (
	  '\x7b7d'::jsonb,
	  coalesce('0'::smallint, 0),
	  null,
	  coalesce('2024-01-22 14:14:25.252391Z'::timestamptz, now()),
	  null::jsonb[],
	  null,
	  'activation_email'::text,
	  '3'::smallint,
	  coalesce('\x7b7d'::jsonb, '{}'),
	  '1'::smallint,
	  'default'::text,
	  coalesce(null::timestamptz, now()),
	  'available'::river_job_state,
	  coalesce(null::varchar(255)[], '{}')
	) RETURNING id, args, attempt, attempted_at, attempted_by, created_at, errors, finalized_at, kind, max_attempts, metadata, priority, queue, state, scheduled_at, tags
	
```

**Comment by brandur** [comment]
Odd, so the problem is that binary data being sent:

```
2024-01-22 14:14:25.253 UTC [8782] ERROR:  invalid input syntax for type json at character 225
2024-01-22 14:14:25.253 UTC [8782] DETAIL:  Token "\" is invalid.
```

Coming from `'\x7b7d'` which is `{}` in binary.

I can easily repro that:

``` go
platform_main_test=# select '\x7b7d'::jsonb;
ERROR:  invalid input syntax for type json
LINE 1: select '\x7b7d'::jsonb;
               ^
DETAIL:  Token "\" is invalid.
CONTEXT:  JSON data, line 1: \...
```

But I'd expect the encoded data to still be a non-binary `{}` at that point during insertion, and am not sure what would transform it that way. I'd guess something on the Go side of things?

**Comment by lexor** [comment]
@bgentry Im using `jackc/pgx/v5 v5.5.2`.

**Comment by lexor** [comment]
I created a repository so that you can reproduce the error (https://github.com/lexor/river-args-reproduce).

**Comment by lexor** [comment]
I found the problem. I encounter this error when the default queue exec mode is selected as simple protocol in the pgxpool config (`config.ConnConfig.DefaultQueryExecMode = pgx.QueryExecModeSimpleProtocol`). However pgx says `DefaultQueryExecMode` is incompatible with PGBouncer.

**Comment by brandur** [comment]
@lexor Nice find.

Did you see that PgBouncer now supports prepared statements if you're using transaction pooling as of a few months ago in version 1.21.0? There is a chance that pgx comment about PgBouncer support is outdated now ...

https://www.pgbouncer.org/faq.html#how-to-use-prepared-statements-with-transaction-pooling

**Comment by lexor** [comment]
@brandur Awesome. Thank you!

**Comment by bgentry** [comment]
I’m wondering if there’s something we could/should be doing to check for invalid configurations like this. We could probably check this connection setting in the pgx pool upon driver init, for example. Thoughts @brandur ?

**Comment by brandur** [comment]
@bgentry Yes possibly.

I think before that though, we should verify that this isn't a pgx bug. A simple protocol seems to make sense to me, but why would that cause pgx to start sending `jsonb` as raw bytes when Postgres seems to clearly not support that?

**Comment by bgentry** [comment]
There’s a bit of a reference to something like this being impossible in this test comment https://github.com/jackc/pgx/blob/517c654e2cfa7f953bf3e7ac44fe2260cfde669a/stdlib/sql_test.go#L607

Want to ask Jack to confirm?

**Comment by nanmu42** [comment]
Sorry to bump this up. I am using River with uptrace/bun and just met this problem. 

Versions:

* github.com/riverqueue/river v0.11.4
* github.com/uptrace/bun v1.2.1
* github.com/jackc/pgx/v5 v5.6.0

The thing is that Bun suggests using `config.DefaultQueryExecMode = pgx.QueryExecModeSimpleProtocol` because it does not benefit from the statement caching:

* https://github.com/uptrace/bun/issues/997
* https://bun.uptrace.dev/postgres/#pgx

I have seen https://github.com/riverqueue/river/pull/234 and wonder if it can be carried out. Or can I help with it? (a how-to would be appreciated)

Thanks for building River, great tool with great taste! I really fancy the idea of using one transaction for job enqueuing and business writes.

**Comment by bgentry** [comment]
@nanmu42 can you possibly provide some more info on what you're running into here and how you're triggering it? You're using the River with the `riverdatabasesql` driver and Bun, is that right? And your underlying pgx is configured with the simple protocol, which is required by Bun.

A bit more detail will help us to be able to look into this and hopefully resolve it (whether or not it's related to this existing issue). Thanks!

**Comment by NathanBaulch** [comment]
I've also run into this issue. Bun is the reason for using `QueryExecModeSimpleProtocol` but isn't required to reproduce the error.
Here's a standalone unit test that uses https://github.com/testcontainers/testcontainers-go to provision a clean DB.

```go
func Test_Pgx_QueryExecModeSimpleProtocol_QueueCreateOrSetUpdatedAt(t *testing.T) {
	ctx := context.Background()
	pg := must(postgres.Run(ctx, "postgres:alpine", postgres.BasicWaitStrategies()))
	defer testcontainers.TerminateContainer(pg)
	cfg := must(pgxpool.ParseConfig(pg.MustConnectionString(ctx, "sslmode=disable")))
	cfg.ConnConfig.DefaultQueryExecMode = pgx.QueryExecModeSimpleProtocol
	db := must(pgxpool.NewWithConfig(ctx, cfg))
	driver := riverpgxv5.New(db)
	migrator := must(rivermigrate.New(driver, nil))
	must(migrator.Migrate(ctx, rivermigrate.DirectionUp, nil))
	must(driver.GetExecutor().QueueCreateOrSetUpdatedAt(ctx, &riverdriver.QueueCreateOrSetUpdatedAtParams{Metadata: []byte("{}"), Name: river.QueueDefault}))
	// BOOM!
}

func must[T any](val T, err error) T { if err != nil { panic(err) } return val }
```

**Comment by nanmu42** [comment]
@bgentry , sorry for the late reply.

> You're using the River with the riverdatabasesql driver and Bun, is that right?

Yes it's true.

> And your underlying pgx is configured with the simple protocol, which is required by Bun.

For now, to integrate Bun with River, I am using `pgx.QueryExecModeCacheStatement` as a walkaround, though it's suboptimal - Queries are executed in a single round trip after the statement is cached but [Bun does not benefit from cache](https://bun.uptrace.dev/postgres/#pgx) since it assembles the SQL in the backend without the placeholders.

Supporting `pgx.QueryExecModeSimpleProtocol` in River would be really cool for me.
