### ISSUE TITLE
go1.20 minimal version not go1.21.4

### ISSUE THREAD

**Issue by patryk4815** [riverqueue/river#175]
Can we require minimal "go 1.20" in go.mod?
Are there any features used here from go 1.21.4?

**Comment by brandur** [comment]
@patryk4815 Going to closes this in favor of https://github.com/riverqueue/river/discussions/156, which is on the same subject.

The short version is that River's using some 1.21 features like slog and some minor improvements to the context APIs. It might be possible to remove those, but given where things are at now Go release-wise, it's probably not worth it.

Did you see that Go 1.22 RC 2 was released today? [1] According to [2], the full release is expected in February. So in less than a month than now, according to Go's versioning policy, Go 1.20 will no longer be officially supported. It might be time to try and get an upgrade through.

FWIW, from here on out we'll probably try to support as many major versions as possible, and will try not to use any 1.22 features right away. (i.e. At least 1.21 and 1.22 supported.)

[1] https://go.dev/dl/
[2] https://tip.golang.org/doc/go1.22

**Comment by patryk4815** [comment]
@brandur  👍 
But I Can't use go1.21 😢 Go 1.20 was last release for certain windows/macos version
