### ISSUE TITLE
run validateQueueName on both insert and worker startup?

### ISSUE THREAD

**Issue by jstern** [riverqueue/river#183]
Hi there! Just started trying out river and really like it so far. However, I ran into this situation which seems like it could be improved upon:

1. I created a job with args with this method `func (MyJobArgs) InsertOpts { return river.InsertOpts{Queue: "my-queue"} }`
2. I deployed my application and successfully inserted a job with that queue value, but realized I'd forgotten to add that queue to my worker config (i did the insert using an insert-only client)
3. I deployed again with an entry in the worker config like `"my-queue": {}`
4. The application failed to start with the error `queue name is invalid, see documentation: "my-queue"`

Personally I like hyphens better than underscores but that's not important 😄 it is surprising though that the `Insert` API doesn't enforce the same validation rules around queue names as the `NewClient` API. Shouldn't the library validate the queue name in both situations using the same logic? I see that there's a `validateJobArgs` that only checks job kinds against registered workers, and only does that if workers are registered (which makes sense), but it feels like it should be fine to also have it always check that the job's configured queue _could_ have a workers attached to it.

(Tangential issue: while the error says "see documentation" I didn't really find anything relevant in the docs; I found the validation rules instead by searching for the error in this repo.)

Happy to submit a PR if you agree but don't have the bandwidth ... or maybe there's a reason to enforce in one situation but not the other?

**Comment by bgentry** [comment]
Thanks for reporting @jstern! Should be fixed in #184. I also improved the error message a bit. I'm due to write an additional doc page on queue organization and naming anyway (from https://github.com/riverqueue/river/discussions/177 ), that would probably be a good place to put more info about this.
