### ISSUE TITLE
invalid go version '1.21.4'

### ISSUE THREAD

**Issue by Bradleykingz** [riverqueue/river#185]
Attempting to run ` go install github.com/riverqueue/river/cmd/river@latest` yields the error ` invalid go version '1.21.4': must match format 1.23`

**Comment by Bradleykingz** [comment]
Fixed by updating intelliJ Go version to 1.21.6.

**Comment by brandur** [comment]
@Bradleykingz Thanks for updating the ticket. And yes, I believe that `go.mod` understanding patch versions is a relatively recent feature (well, last couple years anyway), so it makes sense that it was an outdated Go version in the end.
