### ISSUE TITLE
Leadership re-election

### ISSUE THREAD

**Issue by joshchoo** [riverqueue/river#197]
Hi, I was reading through the following SQL query for leadership re-election:

```sql
-- name: LeadershipAttemptReelect :execrows
INSERT INTO river_leader(name, leader_id, elected_at, expires_at)
  VALUES (@name::text, @leader_id::text, now(), now() + @ttl::interval)
ON CONFLICT (name)
  DO UPDATE SET
    expires_at = now() + @ttl::interval
  WHERE
    EXCLUDED.leader_id = @leader_id::text;
```

Please correct me if I'm understanding incorrectly, but does the WHERE clause always evaluate to true, which could cause non-leaders to extend the expiry of the current leader?

Should the intent be to compare against the latest leader_id value instead as follows?

```sql
...
WHERE
    river_leader.id = EXCLUDED.leader_id;
```

**Comment by bgentry** [comment]
Hi @joshchoo, thank you so much for reporting. I think you may be correct, but before I make a change I'm going to strengthen the test coverage around leader election so I can be sure of the problem and validate the fix.
