### ISSUE TITLE
Start doing GitHub releases

### ISSUE THREAD

**Issue by tadejsv** [riverqueue/river#200]
If you start doing Github releases (instead of just pushing tags), any new release that you do will show up on Github feed of anyone that has starred your repository.

For me personally that would be very useful - I plan to use river in a project of mine soon, and it would be easier this way to keep up with new development :)

**Comment by brandur** [comment]
Hi @tadejsv, yes sounds like a good idea. I just created [a release for v0.0.19](https://github.com/riverqueue/river/releases/tag/v0.0.19) (River's latest) and will add a note in our release instructions to do this for future releases.
