### ISSUE TITLE
Expose client id to provide use of column attempted_by in table river_job

### ISSUE THREAD

**Issue by TC5027** [riverqueue/river#203]
In table river_job there is a column attempted_by which corresponds to which client processed the job. Value inside is the client id. Problem is that this client id is not exposed / can't be accessed making attempted_by column kinda useless, non-informative.

**Comment by TC5027** [comment]
https://github.com/riverqueue/river/pull/204

**Comment by bgentry** [comment]
@TC5027 also see #206 to expose the client ID as a config option and make it programmatically accessible via a new `ID()` method on the `Client` type. Thanks for bringing this up!
