### ISSUE TITLE
[DOCS]: riverqueue.com: poorly rendered <code> snippets.

### ISSUE THREAD

**Issue by neilotoole** [riverqueue/river#210]
Howdy lads,

I just came across your project, I really like what you're building. I'm going to give it a try shortly.

One minor nitpick: the code block rendering on the docs site renders the markdown backtick. I presume this is accidental? If intentional... I don't think it works. E.g. these two particularly egregious tickfests:

<img width="851" alt="backticks" src="https://github.com/riverqueue/river/assets/6013203/aa7fe6d9-31a2-411e-bce1-b6b8b305de80">

From: https://riverqueue.com/docs/batch-job-insertion

Keep up the good work, looking forward to trying it out.

**Comment by bgentry** [comment]
Thanks @neilotoole, this has been bugging me since I set up the site and your comment reminded me to take care of it. Should be all good now ✨

**Comment by neilotoole** [comment]
> this has been bugging me

@bgentry I would have been deeply disappointed if this critical issue hadn't been bothering you! 😜

While you're in there... on the [same page](https://riverqueue.com/docs/batch-job-insertion), I suspect you're missing the code fence for on two links:

<img width="851" alt="needs_code_fence" src="https://github.com/riverqueue/river/assets/6013203/6402c7c4-d4c0-4bb1-bfac-59cae7afb3ad">

In the interest of not consuming all your time: I imagine you're using some sort of static site generator like Hugo, backed by a GH repo? Have you considered making that repo public so PRs can be submitted?

For the docs site for my main side project, [sq](https://github.com/neilotoole/sq), I enabled some Hugo setting, and it shows an _Edit this page on GitHub_ link. E.g. if you scroll to the bottom of [this page](https://sq.io/docs/diff), you'll see a link:

<img width="657" alt="sq_edit_on_github" src="https://github.com/riverqueue/river/assets/6013203/b3425a2b-34c2-46a8-afe9-8b17db6c9d20">

**Comment by brandur** [comment]
FYI, the visible backticks come from Tailwind's typography plugin. It's a stylistic thing for sure, but I don't know, I think they look good.

https://tailwindcss.com/docs/typography-plugin

> While you're in there... on the [same page](https://riverqueue.com/docs/batch-job-insertion), I suspect you're missing the code fence on two links:

Fix those two.

> For the docs site for my main side project, [sq](https://github.com/neilotoole/sq), I enabled some Hugo setting, and it shows an Edit this page on GitHub link. E.g. if you scroll to the bottom of [this page](https://sq.io/docs/diff), you'll see a link:

Yeah, we might want to do that eventually. The docs repo is still in somewhat rough shape though, so we probably wouldn't make it public without an overhaul.

**Comment by neilotoole** [comment]
> but I don't know, I think they look good.

I was in two minds about the ticks when I first saw them on the site, but whether or not the look has appeal, this:

<img width="411" alt="image" src="https://github.com/riverqueue/river/assets/6013203/d049907b-122c-473f-9e3c-9c90834556d6">

... is not a good outcome.

> The docs repo is still in somewhat rough shape though, so we probably wouldn't make it public without an overhaul.

Roger that. I think it looks very solid overall fwiw 👍
