### ISSUE TITLE
Add periodic jobs dynamically

### ISSUE THREAD

**Issue by Catgroove** [riverqueue/river#242]
Based on the current documentation, it seems like it's only possible to add periodic jobs during client creation. It would be nice to be able add periodic jobs after the client has been created, similar to what you can do with scheduled jobs.

Why?

It might be a niche use case, but I have this requirement to react to events in a message driven system, and based on those events I want to create or delete periodic jobs dynamically. river would be a perfect use case for this if this feature was available.

**Comment by bgentry** [comment]
Hi @Catgroove, this is something we’ve been thinking about and are hoping to implement at some point.

Meanwhile, is there any chance your use case would be served by a combination of periodic and unique jobs? Depending on how these jobs are structured it should be possible to set up unique jobs that will insert at most once every N minutes. This would mean your event consumer could always try to insert the relevant event for a given timeframe and would quietly skip the insert if one already exists for that timeframe.

**Comment by Catgroove** [comment]
> Hi @Catgroove, this is something we’ve been thinking about and are hoping to implement at some point.
> 
> Meanwhile, is there any chance your use case would be served by a combination of periodic and unique jobs? Depending on how these jobs are structured it should be possible to set up unique jobs that will insert at most once every N minutes. This would mean your event consumer could always try to insert the relevant event for a given timeframe and would quietly skip the insert if one already exists for that timeframe.

Thanks for the suggestion, but I'm afraid the use case is more complicated than what this solution allows. The interval could change based on the message, so there's this need of both adding, removing, and changing how a job is setup, everytime a message is consumed.

**Comment by JoshuaWilkes** [comment]
I have a related use-case where I would like to be able to enable and disable periodic jobs based on some user controlled config that is updated in an API call.

As it is now I think the only way to handle this would be stopping and restarting a river client.

So being able to do the following would be nice
1. Add a periodic job at runtime
2. Have a mechanism to cancel a periodic job (and any existing enqueued jobs)

**Comment by juicycleff** [comment]
This is a deal breaker for our use case also. I’m considering using a schedule that schedules itself after it’s done to fake a dynamic periodic task but that’s far from elegant but I’m hoping it suffices until maybe this feature is supported.

I love how Riverqueue is design. Appreciate what you guys have built. Thank you

**Comment by brandur** [comment]
I just cut v0.2.0, which includes this feature.

Some docs here:

https://riverqueue.com/docs/periodic-jobs#adding-periodic-jobs-after-client-start
