### ISSUE TITLE
Mistake in testing docs?

### ISSUE THREAD

**Issue by assembly-winston** [riverqueue/river#349]
In the [last section](https://riverqueue.com/docs/testing#testing-workers) under Test Helpers, it looks like there is a typo. 

> Workers in River are plain old Go structs, and no special testing utilities are provided for them. They're testable by initializing a work, invoking its Work function, and checking against the results:

```
func (w *SortWorker) Work(ctx context.Context, job *river.Job[SortArgs]) error {
    sort.Strings(job.Args.Strings)
    fmt.Printf("Sorted strings: %+v\n", job.Args.Strings)
    return nil
}

func TestSortWorker(t *testing.T) {
    err := (&SortWorker{}).Run(ctx, &river.Job{Args: JobArgs{
    //                     ^ shouldn't this say *Work*, not *Run*
        Strings: []string{
          "whale", "tiger", "bear",
        },
    }
    if err != nil {
        // handle error
    }
}
```

**Comment by bgentry** [comment]
Thank you, fixed and will be deployed shortly 🙏🏻
