### ISSUE TITLE
UniqueOpts with ByTags argument

### ISSUE THREAD

**Issue by mobiletoly** [riverqueue/river#368]
We do have ByArgs argument in UniqueOpts but unfortunately it is not good enough for my use case to describe uniqueness of the job (because I have different timestamps, requests id etc in job arguments). Is it possible to add something like ByTags to UniqueOpts for more fine-grained uniqueness control?

**Comment by bgentry** [comment]
@mobiletoly would it work if you could do uniqueness comparisons against a _subset_ of args (specified by top level JSON field names) instead of all of them? That’s something we’ve talked about before but haven’t yet got around to implementing.

**Comment by mobiletoly** [comment]
hi @bgentry - yes, it will absolutely work for me.

**Comment by bgentry** [comment]
This should be closed by #590 which will be merged shortly. You can now opt into having uniqueness considerations look at a subset of your job's arguments, instead of all of them.
