### ISSUE TITLE
In which case, it will cause the 'INFO Notifier: Listener closing'?

### ISSUE THREAD

**Issue by RidaLiu** [riverqueue/river#384]
Hi

I'm running the service locally successfully, but when I migrate to AWS, it reports the log like '
2024/06/10 09:11:16 INFO Notifier: Listener connecting
2024/06/10 09:11:16 INFO Notifier: Listening on topic topic=river_leadership
2024/06/10 09:11:16 INFO Notifier: Listener closing'

the log doesn't show more details, so in which case it will report this kind of issue? 

my code is below, but I don't think it's caused by this func. 
```go
func NewPostgresPool(c *conf.DataService, logger *zap.Logger) (*pgxpool.Pool, error) {
	dbc := c.Postgresql
	logTask := "CREATE_POSTGRES_POOL"
	// Replace special char
	encodedPassword := url.QueryEscape(dbc.Password)
	// river as the alternative schema
	connectionString := fmt.Sprintf(
		"postgres://%s:%s@%s/%s?search_path=%s",
		dbc.Username,
		encodedPassword,
		dbc.Dblink,
		dbc.DbName,
		"river",
	)
	ctxWithTimeout, cancel := context.WithTimeout(context.Background(), dbc.ConnectTimeout.AsDuration())
	defer cancel()
	dbPool, err := pgxpool.New(ctxWithTimeout, connectionString)
	if err != nil {
		logger.Error(logTask, zap.String(bl.ErrorKey, err.Error()), zap.String(bl.ExecStatus, bl.ExecStatusFail))
		return nil, perr.ErrorInternalDatabaseError("%s, err: %s", logTask, err.Error())
	}
	logger.Info(
		logTask,
		zap.Bool("IsPingTestSuccess", dbPool.Ping(ctxWithTimeout) == nil),
	)
	return dbPool, nil
}
```

**Comment by brandur** [comment]
Probably the most likely explanations are that the River client is stopping or there was a bad startup error somewhere. Are there no other non-notifier logs around the ones you pasted?

**Comment by RidaLiu** [comment]
> Probably the most likely explanations are that the River client is stopping or there was a bad startup error somewhere. Are there no other non-notifier logs around the ones you pasted?

it seems that it's caused by the database issue? '''"error":"error listening on topic \"river_leadership\": ERROR: could not access status of transaction 150929435 '''

**Comment by bgentry** [comment]
This seems pretty likely to be an issue with your Postgres installation and not related to River. [Here's a thread](https://www.postgresql.org/message-id/flat/VE1PR03MB531295B1BDCFE422441B15FD92499%40VE1PR03MB5312.eurprd03.prod.outlook.com#7e36d1fdca921b5292e92c7017984ffa) from a few hours where somebody reports running into a similar issue when using `LISTEN`.

One thing you could try is to use poll-only mode (see `PollOnly` on `Config` [here](https://pkg.go.dev/github.com/riverqueue/river#Config)).

Unfortunately I don't think there's anything we could do to help with this or fix it, so I'll close the issue here. Please let us know if you find any more info that suggests this is a problem with River!

**Comment by RidaLiu** [comment]
> This seems pretty likely to be an issue with your Postgres installation and not related to River. [Here's a thread](https://www.postgresql.org/message-id/flat/VE1PR03MB531295B1BDCFE422441B15FD92499%40VE1PR03MB5312.eurprd03.prod.outlook.com#7e36d1fdca921b5292e92c7017984ffa) from a few years ago where somebody reports running into a similar issue when using `LISTEN`.
> 
> One thing you could try is to use poll-only mode (see `PollOnly` on `Config` [here](https://pkg.go.dev/github.com/riverqueue/river#Config)).
> 
> Unfortunately I don't think there's anything we could do to help with this or fix it, so I'll close the issue here. Please let us know if you find any more info that suggests this is a problem with River!

Thanks, PollOnly is helpful, it's fixed.
