### ISSUE TITLE
Python support for river?

### ISSUE THREAD

**Issue by geekodour** [riverqueue/river#397]
Any suggestions on how could one use river from python?

Seems like https://pypi.org/project/riverqueue/ is dead and then there's https://github.com/riverqueue/riverqueue-ruby

If it makes sense to write a port in python, can try a fork. Would love to know what's the consensus here is.

**Comment by brandur** [comment]
Hey @geekodour, @ewhauser wrote a totally awesome Python port over at https://github.com/ewhauser/riverqueue-py.

I think we will be publishing it to PyPi at some point soon, but we still need to do a little more work to get that point. (That's on me.)

**Comment by geekodour** [comment]
thanks! great to know, will head over, looking forward :)

**Comment by brandur** [comment]
Heads up that the Python package is now being formally published to PyPI:

https://pypi.org/project/riverqueue/

And is documented over on the River docs site:

https://riverqueue.com/docs/python
