### ISSUE TITLE
Default tags to [] in the database

### ISSUE THREAD

**Issue by bgentry** [riverqueue/river#46]
From https://github.com/riverqueue/river/pull/44#issuecomment-1819170445:

> The other strong contender here is to make tags NOT NULL and DEFAULT [] in the database, so it becomes always not-nil and an empty array on any job row that comes back.

**Comment by bgentry** [comment]
@brandur thought about this more today and realized now that we've shipped this would require a new DB migration to be added. Maybe we want to hold off and batch it together with other such changes?

**Comment by brandur** [comment]
@bgentry Only other option is to YOLO and have a policy that first day installs are going to need a remigrate. TBH, I think that's okay personally, but has to be done fast.
