### ISSUE TITLE
MPL2.0 license?

### ISSUE THREAD

**Issue by chrnorm** [riverqueue/river#47]
This project looks great, congratulations on the release. I’ve come into the Go ecosystem from Python and always appreciated the simplicity of Celery with Django.

I’d love to adopt this in some of my projects but am concerned about the LGPL license as Go would statically link the library and I’d need to license my application source code with LGPL. I saw [this thread with some more info](https://softwareengineering.stackexchange.com/questions/179084/is-there-a-modified-lgpl-license-that-allows-static-linking) which described projects like zeromq having a static linking exception, but I couldn’t find any exception in the license files for this repo. There was also this post on [LGPL for Go](https://www.makeworld.space/2021/01/lgpl_go.html) which I found a useful reference.

Would you consider licensing this project with MPL2.0?

**Comment by bgentry** [comment]
Thanks for opening this issue @chrnorm, we'll do a bit more research on this topic and make sure this gets sorted out quickly 🙏

**Comment by kamikazechaser** [comment]
First of all, great work on this library!

If the philosophy of this library is to be copyleft i don't mind seeing a _any-GPL_ license on it. I personally wouldn't even mind seeing a more hardcore copyleft license like AGPL-3 license on this. The risk is that is potentially alienates some entities but it does protect this project if any sort of monetization/commercialization is on the roadmap.

See https://en.wikipedia.org/wiki/Free-software_license#Restrictions

**Comment by xzile** [comment]
Another decent list of licenses in the google/go-licenses project: https://github.com/google/go-licenses/blob/master/licenses/types.go

If you want to allow commercial products to integrate the library, I'd avoid any listed as `Forbidden` or `Restricted`.  We internally scan our Go projects using the tool above and reject builds that include libraries with licenses matching forbidden, restricted, or unknown.

**Comment by bgentry** [comment]
License has been updated to MPL2.0, we'll cut a new release soon to reflect this. Thanks all, happy queueing :v:
