### ISSUE TITLE
sql syntax error when listing jobs with database/sql

### ISSUE THREAD

**Issue by uniquefine** [riverqueue/river#478]
Hi, I just updated to the newest river version 10.1 and started using the database/sql driver.

Listing jobs results in the following sql query with syntax errors.
```sql
SELECT
  id, args, attempt, attempted_at, attempted_by, created_at, errors, finalized_at, kind, max_attempts, metadata, priority, queue, state, scheduled_at, tags

FROM
  river_job
WHERE

	kind = any([human elve dwarf]::text[])
  AND state = any([available running]::river_job_state[])

ORDER BY

  id ASC

LIMIT 100::integer
```
Note, the string array literals are incorrect. They should be `{human, elve, dwarf}` cc.

The kinds and states are added to the named arguments as string slices [here](https://github.com/riverqueue/river/blob/bf61772d4693ed498f66a7e1697819554bf3f0cb/internal/dblist/db_list.go#L76). 
And [here](https://github.com/riverqueue/river/blob/bf61772d4693ed498f66a7e1697819554bf3f0cb/riverdriver/riverdatabasesql/river_database_sql.go#L322) the string slices are formatted.

If you want I can create a PR to fix it by type asserting the named parameters and formatting them correctly.

**Comment by bgentry** [comment]
Resolved by #481, release should go out shortly. Thanks for reporting!
