### ISSUE TITLE
[docs] syntax errors in "Error and panic handling"

### ISSUE THREAD

**Issue by brasic** [riverqueue/river#479]
I noticed that the code examples at https://riverqueue.com/docs/error-handling include some syntax errors, possibly from a past find-and-replace operation. The `job` param is listed in three places as being type `*river.rivertype.JobRow` which is not legal syntax.

```go
func (*CustomErrorHandler) HandleError(ctx context.Context, job *river.rivertype.JobRow, err error) *river.ErrorHandlerResult {
    fmt.Printf("Job errored with: %s\n", err)
    return nil
}
```

```
 ./prog.go:6:81: syntax error: unexpected . in parameter list; possibly missing comma or )
```

**Comment by brandur** [comment]
Thanks again. Just updated those signatures as well.
