### ISSUE TITLE
Is it possible or planned to have jobs be queuable for a specific time in the future?

### ISSUE THREAD

**Issue by endigma** [riverqueue/river#48]
Like at a particular date and time, instead of periodically. It would also ideally handle if the worker wasn't running when the task was scheduled, maybe with configurable action in that scenario.

**Comment by bgentry** [comment]
Indeed, thanks for chiming in @linux2647. I’ll get better documentation up on this feature soon.

**Comment by bgentry** [comment]
Additional documentation for this feature is now live: https://riverqueue.com/docs/scheduled-jobs

Thank you again for raising the issue :v:
