### ISSUE TITLE
[docs] incorrect example in "Limiting Retry Attempts"

### ISSUE THREAD

**Issue by brasic** [riverqueue/river#489]
In the docs section on [limiting retry attempts](https://riverqueue.com/docs/job-retries#limiting-retry-attempts), the provided example suggests implementing the `JobArgsWithInsertOpts` interface on a `JobArgs` struct as follows:

```go
func (args *RetryOnceJobArgs) InsertOpts() river.InsertOpts {
    return river.InsertOpts{MaxAttempts: 1}
}
```

But `JobArgs` are passed by value so the [type assertion against that interface](https://github.com/riverqueue/river/blob/01c3dcfd7d622515bb5c61b4f134831570f71764/client.go#L1160) will not succeed if the `InsertOpts` method has a pointer receiver, causing the persisted `max_attempts` value to fall back to the client default. The example works if modified to use a value receiver:

```go
func (args RetryOnceJobArgs) InsertOpts() river.InsertOpts {
    return river.InsertOpts{MaxAttempts: 1}
}
```

**Comment by bgentry** [comment]
Thank you @brasic for reporting :pray: I just fixed that issue.
