### ISSUE TITLE
Allow customize context used in Work func with provided key/values in Insert

### ISSUE THREAD

**Issue by TC5027** [riverqueue/river#513]
Currently the context used in Work function is not linked with the one used in Insert.
I have a use case where I would like to bring a metadata (contained in the context I use to insert) into the context used in Work function

I will try to submit a PR for this

**Comment by bgentry** [comment]
This is not possible or even desirable in River. Your jobs will be worked with a child of the context you pass to the client that _works_ them, but this has no connection to the client which _inserts_ the jobs.

**Comment by rgalanakis** [comment]
If I understand the request correctly, I was originally confused by how to do this sort of thing- @TC5027 if you have 'globals' you want to pass to the work, you should store them on the worker. Like:

```go
type Args struct {
	DocumentId sometypes.DocumentId
}

func (Args) Kind() string { return "my job" }

type Worker struct {
	river.WorkerDefaults[Args]
        client SomeClient
}

type Input struct {
  Client SomeClient
}

func New(input Input) river.Worker[Args] {
	return &Worker{client: input.Client}
}
```

func (w *Worker) Work(ctx context.Context, rjob *river.Job[Args]) error {
  return w.client.DoThingWithId(rjob.Args.DocumentId)
}

// And where you create your worker:
river.AddWorker(workers, myworker.New(myworker.Input{Client: myAppGlobals.Client}))
```

That will make this shared `Client` object available to all jobs.

**Comment by TC5027** [comment]
Thanks for your response :) 
Indeed after looking at the river's code the natural way to perform what i want is to incorporate in job's args.
My use case was to pass user-agent data stored in the context to the `Work` func (ideally in the context directly to be able to use the same piece of code for retrieval)
