### ISSUE TITLE
docs: riverpro missing line type workflows -> workflow 

### ISSUE THREAD

**Issue by krhubert** [riverqueue/river#546]
Hi,

When I run cli with `--line workflows` it panics.

```
riverpro migrate-up --database-url  "postgres://postgres:@localhost:5432/postgres" --line workflows
panic: migration line does not exist: workflows
```

But with `--line workflow` all is good

```
riverpro migrate-up --database-url  "postgres://postgres:@localhost:5432/postgres" --line workflow
```

Links with typos

https://riverqueue.com/docs/pro/go-proxy#installing-in-ci-and-build-environments
https://riverqueue.com/docs/pro/getting-started#running-pro-migrations

**Comment by brandur** [comment]
Thanks Hubert!

Wow, believe it or not, we've had multiple people run through those steps already, but you're the first to report the problem to us :/

I just pushed a fix. We should really also have some basic [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) check that'd be able to detect a one letter difference and suggest a correction too. I'll look into that separately.

Please don't hesitate to open any more bug reports if you find other problems!

**Comment by krhubert** [comment]
Sure, I was quite surprised that nobody ran into trouble with this one. Awesome it is fixed so fast. I'll open issues as they raise. I actually have one more already.

**Comment by brandur** [comment]
Going to try and do one other small follow up here to suggest alternatives when a migration line is found to be non-existent in #558.
