### ISSUE TITLE
Typo in code example in docs

### ISSUE THREAD

**Issue by HenryDashwood** [riverqueue/river#588]
Hello, just getting set up on riverpro and tripped up on the workflows example code here.

Should 

```go
func SampleWorkflow() *river.Workflow {
```

actually be

```go
func SampleWorkflow() *riverworkflow.Workflow {
```

?

<img width="807" alt="image" src="https://github.com/user-attachments/assets/297edea8-4157-4c58-ace7-85ae72a540dc">

**Comment by bgentry** [comment]
@HenryDashwood yes, it absolutely should, I'll get that fixed up right away. Thank you!

Feel free to ping on the support email for anything Pro related like this or if you want to open a more direct line of communication.

**Comment by HenryDashwood** [comment]
Me again! Also in the workflows section of the docs there is this line:

```go
    // Complete the current task:
    if err := riverClient.JobCompleteTx[*riverpgxv5.Driver](ctx, tx, job); err != nil {
        return err
    }
 ```

should this actually be `river.JobCompleteTx...`?

**Comment by bgentry** [comment]
Thanks @HenryDashwood, a fix for that one should be deployed in a minute or so. Non-executable example code is an endless project 😆 

I'll be taking another comprehensive pass through these docs soon due to some upcoming changes, I'll see if there's more I can do to validate them in the process.
