### ISSUE TITLE
v0.12.0 all tasks go to the status discarded with `InsertTx`

### ISSUE THREAD

**Issue by sxwebdev** [riverqueue/river#618]
After upgrading to version 0.12.0 all my new tasks created in the following way:

```go
riverClient.InsertTx(ctx, dbTx,
	taskmanager.SomeArgs{
		Key: value,
	},
	&river.InsertOpts{
		UniqueOpts: river.UniqueOpts{
			ByArgs: true,
		},
		ScheduledAt: time.Now().Add(time.Second*30),
	},
)
```

Began to be marked in the database with the status "discarded"

This problem was solved only in this way:

```go
func (s *Worker) InsertOpts() river.InsertOpts {
	return river.InsertOpts{
		UniqueOpts: river.UniqueOpts{
			ByArgs: true,
		},
	}
}
```

It looks like unique parameters are ignored at the task creation level.

Before updating to version 0.12.0, I rolled out migrations from scratch

**Comment by bgentry** [comment]
I’m not clear on what’s happening or what actually fixed it. You’re saying that you were using using insert time `UniqueOpts` on a prior version with only `ByArgs` with no problems? And after upgrading, your jobs are somehow being inserted directly into a `discarded` stste?

I don’t think the `discarded` state can ever be reached at insert time without the job executing first and having errors, which is why this confuses me. However I don’t doubt that _somerhing_ broke here and It’s likely prettt important. Are there any other logs you can provide, or a minimal code sample to reproduce?

**Comment by bgentry** [comment]
@sxwebdev I've found at least one bug here that's new to v0.12.0. While I've fixed that one locally, I'm working on additional test cases and making sure all edge cases are covered. Hope to have something up shortly.

**Comment by sxwebdev** [comment]
@bgentry thank you, waiting for the release

**Comment by bgentry** [comment]
@sxwebdev I believe #619 should address the issue you ran into along with another one I found. Added missing coverage to ensure it's fixed and doesn't break again. I'll ship that shortly in a v0.12.1.

Really sorry about the issue here, thank you so much for reporting it.

**Comment by bgentry** [comment]
@sxwebdev ok [v0.12.1](https://github.com/riverqueue/river/releases/tag/v0.12.1) should be live now (barring any of the annoying issues with go module proxy caching), can you give that a try and let me know if you see anything else fishy? Thank you again :pray:

**Comment by sxwebdev** [comment]
@bgentry Hi. I just rolled back my changes.

Removed this:

```go
func (s *Worker) InsertOpts() river.InsertOpts {
	return river.InsertOpts{
		UniqueOpts: river.UniqueOpts{
			ByArgs: true,
		},
	}
}
```

Returned this:

```go
riverClient.InsertTx(ctx, dbTx,
	taskmanager.SomeArgs{
		Key: value,
	},
	&river.InsertOpts{
		UniqueOpts: river.UniqueOpts{
			ByArgs: true,
		},
		ScheduledAt: time.Now().Add(time.Second*30),
	},
)
```

And updated the river to `0.12.1`

In other words, I did it as it was before.

Now everything works as before version `0.12`. The problem is no longer observed, thanks for the promptness.
