### ISSUE TITLE
v0.0.8 migration fails when there are existing jobs with `NULL` tags

### ISSUE THREAD

**Issue by vito** [riverqueue/river#63]
I've got a database with a bunch of jobs still around in `completed` state, which causes the migration to fail:

```
failed: error applying version 003 [UP]: ERROR: column "tags" of relation "river_job" contains null values (SQLSTATE 23502)
```

Seems like the migration could update all existing rows to have `[]`, assuming there's a way to do that without race conditions. I guess you'd have to [lock the entire table](https://www.postgresql.org/docs/current/sql-lock.html)?

In my case I think I'll just `TRUNCATE` or `DELETE FROM` the full `river_job` table prior to running the migration.

**Comment by bgentry** [comment]
@vito ugh, I got a bit too excited shipping this change and forgot the obvious need to do it in a couple steps  🤦‍♂️ 

Will ship a fix shortly that fixes the existing migration in place since it can’t succeed on existing installs.

**Comment by bgentry** [comment]
Thanks @vito, [v0.0.9](https://github.com/riverqueue/river/releases/tag/v0.0.9) has been released with a corrected migration. Sorry for the trouble! We still have some work to do on making the tests more robust to prevent this kind of oversight from slipping in.

**Comment by vito** [comment]
Thanks @bgentry - that was fast!
