### ISSUE TITLE
Importing rivertest

### ISSUE THREAD

**Issue by mgomes** [riverqueue/river#645]
According to the [docs](https://riverqueue.com/docs/testing), I should be able to import the `rivertest` package. However, I don't see it in the `go.work` file and it's failing to import for me.

```
▶ go get -t <my-module>
go: github.com/riverqueue/river/rivertest@v0.13.0: reading github.com/riverqueue/river/rivertest/go.mod at revision rivertest/v0.13.0: unknown revision rivertest/v0.13.0
```

My go.mod imports for river:

```go
github.com/riverqueue/river v0.13.0
github.com/riverqueue/river/riverdriver/riverpgxv5 v0.13.0
github.com/riverqueue/river/rivertest v0.13.0
```

Am I doing something wrong?

**Comment by bgentry** [comment]
Hmm, is there any more to the failure message or is that it? The module [shows up on Go docs](https://pkg.go.dev/github.com/riverqueue/river@v0.13.0/rivertest) just fine 🤔 

You may be able to get more details with a `-v` flag.
