### ISSUE TITLE
Achieving debounce effect with Unique options

### ISSUE THREAD

**Issue by emilecaron** [riverqueue/river#646]
Hello 

I'm having a hard time figuring out how to achieve a debounce like effect using the current UniqueOpts configuration.
My goal is to have at any time at most one job running, and another waiting to be executed.

Is this something that can be done with the current options ? 

Thanks

**Comment by kamikazechaser** [comment]
>  My goal is to have at any time at most one job running, and another waiting to be executed.

Setting MaxWorkers: 1 on that queue should achieve that affect.

**Comment by emilecaron** [comment]
i didn't mention that i need to use the ByArgs unique configuration. I may have several jobs running and pending as long as their params are different. 
So i think a dedicated single worker queue is unfortunately not an option in my case
