### ISSUE TITLE
Docs: finding migrations files

### ISSUE THREAD

**Issue by WillAbides** [riverqueue/river#657]
The [migrations doc on riverqueue.com](https://riverqueue.com/docs/migrations) has a couple of "migrations directory" links pointing to https://github.com/riverqueue/river/tree/master/rivermigrate/migration. It suggests going there and looking for the highest number migration. The linked directory doesn't directly contain any migrations. Instead it has three subdirectories that each have a different number of migrations. I ended up finding https://github.com/riverqueue/river/tree/v0.13.0/riverdriver/riverpgxv5/migration/main and using it to confirm that 006 is the newest migration for v0.13.0.

**Comment by bgentry** [comment]
Thanks for reporting these! It's probably not the best advice to tell you to go to the source code anyway, so I fixed each of these to primarily reference the `river migrate-list` CLI command, though I left one link to the _correct_ source code in place too.
