### ISSUE TITLE
Docs: It could be clearer that all periodic jobs need to be configured on every client

### ISSUE THREAD

**Issue by WillAbides** [riverqueue/river#658]
I had to do some troubleshooting to discover why some of my periodic jobs weren't working. It turns out it's because I didn't understand that only the current leader's periodic jobs get queued even though I had read [the periodic jobs doc](https://riverqueue.com/docs/periodic-job). In hindsight this is mentioned under "Details and caveats", but when I read that initially my only takeaway was that some jobs might get skipped due to the timing of leader elections. It would be nice if it were spelled out more clearly that all jobs need to be configured on every client that could potentially be the leader.

Also, in case opening two doc issues in a day gives the impression that I find River's docs lacking, it's quite the opposite. River's docs are great and have made adoption go very smoothly.

**Comment by bgentry** [comment]
Thank you for the suggestion and I'm glad you're finding the docs helpful! 😄 I just pushed a note to [the periodic jobs doc](https://riverqueue.com/docs/periodic-jobs). I felt the "details and caveats" section was still the best place for it, though I'm also thinking that would benefit from being broken out a bit and may do that soon.
