### ISSUE TITLE
Middleware for Periodic Jobs (Tracing)

### ISSUE THREAD

**Issue by mfrister** [riverqueue/river#675]
While adding tracing, I've noticed that periodic jobs are inserted without going through middleware configured on the Client - it looks like [PeriodicJobEnqueuer's insertBatch](https://github.com/riverqueue/river/blob/cef224550afab3ec9dc20b6f793e1d62964e6137/internal/maintenance/periodic_job_enqueuer.go#L332) goes directly to the River driver instead of going through the client.

For completeness of the trace (job may be scheduled earlier than actually run if workers are busy), it would be nice to be able to intercept periodic job insertion in middleware.

**Comment by bgentry** [comment]
@mfrister Thanks for catching this! I'll have a v0.14.2 out shortly with this fix from #679 in it. :v:
