### ISSUE TITLE
Password in database URL should url encode special characters

### ISSUE THREAD

**Issue by flamendless** [riverqueue/river#676]
Hi, if `DATABASE_URL` is used with password that is randomly generated with special characters such as `{` and `}` (like from AWS) an error occurs `failed: error parsing database URL: cannot parse 'postgres://root:xxxxxx@localhost:5432/dbname': failed to parse as URL
(net/url: invalid userinfo)`

Errors: `river migrate-up --database-url "postgres://root:a{a}@localhost:5432/dbname"`
Works: `river migrate-up --database-url "postgres://root:a%7Ba%7D@localhost:5432/dbname"`

**Comment by brandur** [comment]
So this one comes right from Go itself (`net/url` called from within Pgx):

``` go
package main

import (
	"fmt"
	"log"
	"net/url"
)

func main() {
	u, err := url.Parse("postgres://user_with_weird_password:password_containing_{}_and_stuff@localhost:5432/river_test")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("URL:", u)
}
```

```
2009/11/10 23:00:00 parse "postgres://user_with_weird_password:password_containing_{}_and_stuff@localhost:5432/river_test": net/url: invalid userinfo

Program exited.
```

Curiously, psql does seem to tolerate the bad characters:

```
psql "postgres://user_with_weird_password:password_containing_{}_and_stuff@localhost:5432/river_test"
```

I suppose we could add a layer that tries to detect and translate an invalid looking password, but that might get a little messy. One could also make the argument that Go's behavior is more correct because these aren't valid URL characters.

OOC, this presumably fails when you use it with Pgx too doesn't it? Or do you construct your `Config` object manually to work around it there?

**Comment by flamendless** [comment]
Good day! Yes it fails with `pgx.ParseConfig` and `pgxpool.ParseConfig` too.

**Comment by brandur** [comment]
I did find this Go issue where someone else was complaining about the URL parser being too strict:

https://github.com/golang/go/issues/29808

With a link to an alternative parser that could potentially be configured to allow lax parsing:

https://github.com/nlnwa/whatwg-url

I'm on the fence about trying that out though. I suppose if we were to parse the URL, then inject it into pgx using a configuration struct directly. That wouldn't be too bad, but is kind of weird.

It might be better to support an alternative set of args for host/user/port like psql does:

```
Connection options:
  -h, --host=HOSTNAME      database server host or socket directory (default: "local socket")
  -p, --port=PORT          database server port (default: "5432")
  -U, --username=USERNAME  database user name (default: "brandur")
  -w, --no-password        never prompt for password
  -W, --password           force password prompt (should happen automatically)
```

It doesn't take an injected password, but will read from prompt or from `PGPASSWORD`.

Let's see if someone else complains about this though. It's wishful thinking, but honestly, the most ideal thing would be for providers to stop using URL-incompatible characters in passwords. Provides zero benefit (if you're worried about entropy, you could always make the password a little longer to compensate), and lots of problems. Makes the password hard to copy/paste by double-clicking it, will be shell incompatible if you use things like `$`, etc.
