### ISSUE TITLE
Problems with migrations for 0.12.0

### ISSUE THREAD

**Issue by hypnoglow** [riverqueue/river#688]
[CHANGELOG upgrade guide](https://github.com/riverqueue/river/blob/master/CHANGELOG.md#0120---2024-09-23) recommends running index migration manually for large tables. After that, "normal" river migration should be run to finalize the process.

The problem is that the existing index is [tolerated](https://github.com/riverqueue/river/blob/master/riverdriver/riverdatabasesql/migration/main/006_bulk_unique.up.sql#L28), but the existing column [is not](https://github.com/riverqueue/river/blob/master/riverdriver/riverdatabasesql/migration/main/006_bulk_unique.up.sql#L23), which results in the following error:

```
column "unique_states" of relation "river_job" already exists
```

**Comment by bgentry** [comment]
@hypnoglow hmm, there wasn't a `unique_states` column prior to this migration v6. Did you perhaps try to run that migration line adding that column twice?

**Comment by hypnoglow** [comment]
> there wasn't a unique_states column prior to this migration v6

@bgentry You're right. But your [migration guide](https://github.com/riverqueue/river/blob/master/CHANGELOG.md#0120---2024-09-23) suggests to run the following query to create it manually, because it is used in the index:

```sql
ALTER TABLE river_job ADD COLUMN unique_states BIT(8);

CREATE UNIQUE INDEX CONCURRENTLY river_job_unique_idx ON river_job (unique_key)
    WHERE unique_key IS NOT NULL
      AND unique_states IS NOT NULL
      AND river_job_state_in_bitmask(unique_states, state);
```

Then the guide recommends running river migrator, and so ALTER is executed second time.

**Comment by brandur** [comment]
@hypnoglow Ah yes that's quite right. We'll get a fix shipped for this immediately. Thanks for reporting!

**Comment by hypnoglow** [comment]
Thank you 💙

**Comment by hypnoglow** [comment]
Just FYI

In release descripion https://github.com/riverqueue/river/releases/tag/v0.14.3 PR links are mixed up with each other.

**Comment by bgentry** [comment]
@hypnoglow thanks, fixed the GitHub release and will tweak the changelog too :pray:
