### ISSUE TITLE
DefaultClientRetryPolicy overflows to past

### ISSUE THREAD

**Issue by hypnoglow** [riverqueue/river#697]
In retry mechanism, if we increase `MaxAttempts`, then `DefaultClientRetryPolicy` will overflow at some point and `NextRetry()` will return a date in the past:

```
"message": "jobExecutor: Retry policy returned invalid next retry before current time; using default retry policy instead",
"next_retry_scheduled_at": "1732-09-09T07:24:19.414Z",
"now": "2024-12-19T07:11:36.269Z",
```

UPD: changed the previous hypothesis.

It seems that it only overflows in the logs, where conversion to Unix time happens.

I checked the database and the date is fine:

```
id           | 201477
state        | retryable
attempt      | 305
max_attempts | 1024
attempted_at | 2024-11-20 19:54:13.52567+00
created_at   | 2024-11-08 08:30:37.197066+00
finalized_at | <null>
scheduled_at | 2274-04-14 17:57:33.177419+00
```

But then I also don't understand why our custom policy that is designed to cap retry time doesn't work. Here's the code:

```go
func (p *LimitingRetryPolicy) NextRetry(job *rivertype.JobRow) time.Time {
	nextTime := p.origin.NextRetry(job).  // p.origin is &DefaultClientRetryPolicy{}
	maxTime := p.now().Add(p.threshold) // p.threshold is e.g. time.Hour

	if maxTime.Before(nextTime) {
		return maxTime
	}

	return nextTime
}
```

With this policy we still get retry time that is far beyond our threshold (such as in the logs above).

**Comment by brandur** [comment]
I looked into this a bit, and although I couldn't get the next retry time to overflow, there are some oddities around handling of very large durations that we should at least be explicit about it. The maximum length of the time that can be stored in a duration is about 292 years, and once you start going over that, you're in danger of overflowing it and can get some odd behavior.

I'm not sure how you even got there though. You start hit duration limits at retry 310, but before 310 you're already well into exponential territory, so you'll never actually be hitting those next retries because they're 100s of years out. I see that you got to attempt no. 305 in your record above, but if you using the default policy isn't the distance between attempt 304 and 305 still measured in months?

**Comment by brandur** [comment]
Added #698 to make sure we never overflow `time.Duration`. That should help somewhat, but I suspect you may have some other bug in your stack somewhere ...

**Comment by hypnoglow** [comment]
> I'm not sure how you even got there though. You start hit duration limits at retry 310, but before 310 you're already well into exponential territory, so you'll never actually be hitting those next retries because they're 100s of years out. I see that you got to attempt no. 305 in your record above, but if you using the default policy isn't the distance between attempt 304 and 305 still measured in months?

We have a limiting policy, here's the full code just in case:

<details>

<summary>LimitingRetryPolicy</summary>

```go
// LimitingRetryPolicy wraps another [river.ClientRetryPolicy] and limits the
// maximum time until the next retry.
type LimitingRetryPolicy struct {
	origin    river.ClientRetryPolicy
	threshold time.Duration
	now       func() time.Time
}

func NewLimitingRetryPolicy(
	origin river.ClientRetryPolicy,
	threshold time.Duration,
) *LimitingRetryPolicy {
	return &LimitingRetryPolicy{
		origin:    origin,
		threshold: threshold,
		now: func() time.Time {
			return time.Now().UTC()
		},
	}
}

func (p *LimitingRetryPolicy) NextRetry(job *rivertype.JobRow) time.Time {
	nextTime := p.origin.NextRetry(job)
	maxTime := p.now().Add(p.threshold)

	if maxTime.Before(nextTime) {
		return maxTime
	}

	return nextTime
}
```

</details>

For the problematic job from the first post, here's how last errors look like in `errors` column:

```
"{"at": "2024-11-20T14:54:11.936027434Z", "error": "...", "trace": "", "attempt": 300}",
"{"at": "2024-11-20T15:54:12.211605629Z", "error": "...", "trace": "", "attempt": 301}",
"{"at": "2024-11-20T16:54:12.386373907Z", "error": "...", "trace": "", "attempt": 302}",
"{"at": "2024-11-20T17:54:12.947652177Z", "error": "...", "trace": "", "attempt": 303}",
"{"at": "2024-11-20T18:54:13.104876028Z", "error": "...", "trace": "", "attempt": 304}",
"{"at": "2024-11-20T19:54:13.530701546Z", "error": "...", "trace": "", "attempt": 305}"
```

As we see, the limiting retry policy works fine and retries were set every hour until the last attempt, which is suddenly scheduled to year 2274.

```
select id, state, attempt, max_attempts, attempted_at, created_at, finalized_at, scheduled_at, array_length(errors, 1) as errors_count f
 rom river_job where id = 201477;
-[ RECORD 1 ]-------------------------
id           | 201477
state        | retryable
attempt      | 305
max_attempts | 1024
attempted_at | 2024-11-20 19:54:13.52567+00
created_at   | 2024-11-08 08:30:37.197066+00
finalized_at | <null>
scheduled_at | 2274-04-14 17:57:33.177419+00
errors_count | 305
```

**Comment by brandur** [comment]
Ah right. Yeah, the part I was having a bit of a hard time understanding is how the retry attempts were becoming so frequent. If you were calling down to the default retry policy then anything around attempt 300 would be exponential with months duration between job retries, but as we can see, your jobs are retrying ~3 times/sec.

I believe there might be some odd overflow shenanigans in the 300+ range for sure, but before an overflow, retries should be behaving relatively normally, even before #698.

It looks like in your code `origin` could be another non-default policy though, so presumably you know what you're doing.

**Comment by hypnoglow** [comment]
> If you were calling down to the default retry policy then anything around attempt 300 would be exponential with months duration between job retries, but as we can see, your jobs are retrying ~3 times/sec.

I don't understand where you see ~3 times/sec.

The data from `errors` column above clearly shows that the job is retried each hour. So the limiting policy works fine up until 305 retries. Then it gets to 200+ years.

> It looks like in your code origin could be another non-default policy though, so presumably you know what you're doing.

No, it is default:

```go
	retryPolicy := NewLimitingRetryPolicy(
		&river.DefaultClientRetryPolicy{},
		time.Hour,
	)

	return &river.Config{
		CancelledJobRetentionPeriod: defaultRetentionPeriod,
		CompletedJobRetentionPeriod: defaultRetentionPeriod,
		DiscardedJobRetentionPeriod: defaultRetentionPeriod,
		FetchPollInterval:           c.FetchPollInterval,
		ID:                          id,
		JobTimeout:                  c.JobTimeout,
		RetryPolicy:                 retryPolicy,
	}
```

**Comment by brandur** [comment]
Ah okay, I misread that — it's once an hour rather than 3 times a second. Same comment though. At this range the default policy still measures retries in months — nowhere near once an hour.

Going to  call this one closed via https://github.com/riverqueue/river/pull/698. If there's another issue, happy to look into it, but let's try to have a repro.
