### ISSUE TITLE
Using a separate schema with a pgxpool

### ISSUE THREAD

**Issue by thezachdrake** [riverqueue/river#713]
My ocd needs me to keep my river tables in a separate schema for organization purposes. Their are just simply too many of them to be floating around in public with all the other tables. Not looking to discuss the merits of that here. I am following the guide in the docs: https://riverqueue.com/docs/alternate-schema. I have river tables migrated to this schema and it all looks correct.

Tell me if I am wrong, but it seems like the river client wants the pgx.pool to be configured with `search_path` set to the river schema. The problem is that pgx is not letting me have multiple pools, and the rest of my app needs a general search path that can query other schemas. Is there a good solution to initiating the river client with a search path that doesn't affect the global pgx pool?

**Comment by brandur** [comment]
> The problem is that pgx is not letting me have multiple pools

I'm not sure what you mean by this — pgx for sure lets you have multiple pools.

> Is there a good solution to initiating the river client with a search path that doesn't affect the global pgx pool?

`search_path` lets you add multiple comma separated schemas to it. Maybe do something like `search_path = river, public`?

**Comment by thezachdrake** [comment]
So when I do this:

```
package database

var (
	Db     *pgxpool.Pool
	JobsDb *pgxpool.Pool
	pgOnce sync.Once
)

func NewDB(ctx context.Context) error {
	log.Info("connecting to postgres")
	connString := configs.DbConfig.ConnString()
	pgOnce.Do(func() {
		db, err := pgxpool.New(ctx, connString)
		if err != nil {
			log.Fatal("unable to create connection pool: %w", err)
		}

		Db = db
	})

	log.Info("Postgres connected")
	return nil
}

func NewJobsDB(ctx context.Context) error {
	log.Info("connecting to postgres")
	connString := configs.DbConfig.JobsConnString()
	pgOnce.Do(func() {
		db, err := pgxpool.New(ctx, connString)
		if err != nil {
			log.Fatal("unable to create connection pool: %w", err)
		}

		JobsDb = db
	})

	log.Info("Postgres connected")
	return nil
}
```

and try to initiate the River client on start up with:

```
package jobs

var (
	workers *river.Workers
	Client  *river.Client[pgx.Tx]
)

func New(ctx context.Context) error {
	err := error(nil)

	workers = river.NewWorkers()
	river.AddWorker(workers, &sphinx_snake_jobs.PosCustomersETLWorker{})
	river.AddWorker(workers, &sphinx_snake_jobs.PosOrdersETLWorker{})
	river.AddWorker(workers, &sphinx_snake_jobs.PosProductsETLWorker{})

	Client, err = river.NewClient(riverpgxv5.New(database.JobsDb), &river.Config{
		Logger: slog.New(&slogutil.SlogMessageOnlyHandler{Level: slog.LevelInfo}),
		PeriodicJobs: []*river.PeriodicJob{
			sphinx_snake_jobs.PosCustomersETLJob,
			sphinx_snake_jobs.PosOrdersETLJob,
			sphinx_snake_jobs.PosProductsETLJob,
		},
		Queues: map[string]river.QueueConfig{
			river.QueueDefault: {MaxWorkers: 100},
		}, // suitable only for use in tests; remove for live environments
		Workers: workers,
	})
	if err != nil {
		return err
	}

	return err
}

```

I get an error saying that the client was passed a `nil` pool:
`2024/12/30 13:47:03.074997 main.go:43: [Fatal] must have a non-nil database pool to execute jobs (either use a driver with database pool or don't configure Queues)`

But if I pass the client the `database.Db` it starts up fine and jobs run. I was assuming that it was a multiple pool problem but maybe there is an obvious bug I am just missing here.

**Comment by thezachdrake** [comment]
I found this issue. In the database package I used the same `sync.Once` instance to build both pools. Changing it to this works:

```
package database

var (
	Db       *pgxpool.Pool
	JobsDb   *pgxpool.Pool
	pgOnce   sync.Once
	jobsOnce sync.Once
)

func NewDB(ctx context.Context) error {
	log.Info("connecting to postgres")
	connString := configs.DbConfig.ConnString()
	pgOnce.Do(func() {
		db, err := pgxpool.New(ctx, connString)
		if err != nil {
			log.Fatal("unable to create connection pool: %w", err)
		}

		Db = db
		log.Info("Postgres connected: app")
	})

	return nil
}

func NewJobsDB(ctx context.Context) error {
	log.Info("connecting to postgres")
	connString := configs.DbConfig.JobsConnString()
	jobsOnce.Do(func() {
		db, err := pgxpool.New(context.TODO(), connString)
		if err != nil {
			log.Fatal("unable to create connection pool: %w", err)
		}

		JobsDb = db
		log.Info("Postgres connected: jobs")
	})

	return nil
}

```

**Comment by brandur** [comment]
@thezachdrake Ah great. Yep, that would do it. Okay thanks for checking back in.
